# Generated by Django 3.2.9 on 2022-01-21 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StandardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Elective', 'Elective')], max_length=20)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='standard',
            name='subject',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied', models.CharField(max_length=400)),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='KnowShowChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.CharField(default='Justin', max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Elective', 'Elective')], max_length=20)),
                ('standardSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.standardset')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='know_show_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.knowshowchart'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
        ),
        migrations.AddField(
            model_name='standard',
            name='standardSet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.standardset'),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollments',
            field=models.ManyToManyField(to='api.Enrollment'),
        ),
    ]
