# Generated by Django 3.2.9 on 2022-01-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_knowshowchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowshowchart',
            name='author',
            field=models.CharField(default='Justin', max_length=200),
        ),
    ]
