# Generated by Django 3.2.9 on 2022-01-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_enrollment_standardset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='standardSet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.standardset'),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrollments',
            field=models.ManyToManyField(blank=True, to='api.Enrollment'),
        ),
    ]
