# Generated by Django 3.2.9 on 2022-05-22 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220220_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='students',
            field=models.ManyToManyField(related_name='selectedStudents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teachers',
            field=models.ManyToManyField(related_name='teacherCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
