# Generated by Django 3.2.9 on 2022-06-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_planweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='planweek',
            name='standard_set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.standardset'),
        ),
        migrations.AddField(
            model_name='planweek',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='standardset',
            name='prep_title',
            field=models.CharField(default='Algebra', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planweek',
            name='daily_know_show',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='studentdataentry',
            name='result',
            field=models.JSONField(default=dict),
        ),
    ]
