# Generated by Django 3.2.9 on 2022-06-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220615_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='planweek',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.standard'),
            preserve_default=False,
        ),
    ]
